package cn.sinjinsong.skeleton.domain.entity.mail;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer;

import java.time.LocalDateTime;

public class MailTextDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_text.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_text.send_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    private LocalDateTime sendTime;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_text.mail_text
     *
     * @mbggenerated
     */
    private String mailText;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_text
     *
     * @mbggenerated
     */
    public MailTextDO(Long id, LocalDateTime sendTime, String mailText) {
        this.id = id;
        this.sendTime = sendTime;
        this.mailText = mailText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_text
     *
     * @mbggenerated
     */
    public MailTextDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_text.id
     *
     * @return the value of mail_text.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_text.id
     *
     * @param id the value for mail_text.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_text.send_time
     *
     * @return the value of mail_text.send_time
     *
     * @mbggenerated
     */
    public LocalDateTime getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_text.send_time
     *
     * @param sendTime the value for mail_text.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(LocalDateTime sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_text.mail_text
     *
     * @return the value of mail_text.mail_text
     *
     * @mbggenerated
     */
    public String getMailText() {
        return mailText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_text.mail_text
     *
     * @param mailText the value for mail_text.mail_text
     *
     * @mbggenerated
     */
    public void setMailText(String mailText) {
        this.mailText = mailText == null ? null : mailText.trim();
    }

    @Override
    public String toString() {
        return "MailTextDO{" +
                "id=" + id +
                ", sendTime=" + sendTime +
                ", mailText='" + mailText + '\'' +
                '}';
    }
}