package cn.sinjinsong.skeleton.domain.entity.mail;

import cn.sinjinsong.skeleton.domain.entity.user.UserDO;
import cn.sinjinsong.skeleton.enumeration.mail.MailStatus;

public class MailDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.id
     *
     * @mbggenerated
     */
    private Long id;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.sender
     *
     * @mbggenerated
     */
    private UserDO sender;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.receiver
     *
     * @mbggenerated
     */
    private UserDO receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.mail_status
     *
     * @mbggenerated
     */
    private MailStatus mailStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.text
     *
     * @mbggenerated
     */
    private MailTextDO text;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail
     *
     * @mbggenerated
     */
    public MailDO(Long id, UserDO sender, UserDO receiver, MailStatus mailStatus, MailTextDO text) {
        this.id = id;
        this.sender = sender;
        this.receiver = receiver;
        this.mailStatus = mailStatus;
        this.text = text;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail
     *
     * @mbggenerated
     */
    public MailDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.id
     *
     * @return the value of mail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.id
     *
     * @param id the value for mail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.sender
     *
     * @return the value of mail.sender
     *
     * @mbggenerated
     */
    public UserDO getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.sender
     *
     * @param sender the value for mail.sender
     *
     * @mbggenerated
     */
    public void setSender(UserDO sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.receiver
     *
     * @return the value of mail.receiver
     *
     * @mbggenerated
     */
    public UserDO getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.receiver
     *
     * @param receiver the value for mail.receiver
     *
     * @mbggenerated
     */
    public void setReceiver(UserDO receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.mail_status
     *
     * @return the value of mail.mail_status
     *
     * @mbggenerated
     */
    public MailStatus getMailStatus() {
        return mailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.mail_status
     *
     * @param mailStatus the value for mail.mail_status
     *
     * @mbggenerated
     */
    public void setMailStatus(MailStatus mailStatus) {
        this.mailStatus = mailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.text
     *
     * @return the value of mail.text
     *
     * @mbggenerated
     */
    public MailTextDO getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.text
     *
     * @param text the value for mail.text
     *
     * @mbggenerated
     */
    public void setText(MailTextDO text) {
        this.text = text;
    }

    @Override
    public String toString() {
        return "MailDO{" +
                "id=" + id +
                ", sender=" + sender +
                ", receiver=" + receiver +
                ", mailStatus=" + mailStatus +
                ", text=" + text +
                '}';
    }
}